export { default as Header } from "./Header";
export { default as Profile } from "./Profile";
export { default as Login } from "./Login";
export { default as Register } from "./Register";
export { default as NewPost } from "./NewPost";
export { default as Home } from "./Home";
export { default as Search } from "./Search";
export { default as SinglePost } from "./SinglePost";
export { default as SinglePostPage } from "./SinglePostPage";
